// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbqIDFryQ3HRqQPp37t8DQf7MZehc9H-A',
    appId: '1:343243780822:web:4d652ea09c1543cce50f77',
    messagingSenderId: '343243780822',
    projectId: 'dharbi-3e2b0',
    authDomain: 'dharbi-3e2b0.firebaseapp.com',
    storageBucket: 'dharbi-3e2b0.firebasestorage.app',
    measurementId: 'G-3YTP2E85NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3VlmNhRiAbJBnuQcdvNw-_Fq89RfaNg',
    appId: '1:343243780822:android:3a3fc578194abb79e50f77',
    messagingSenderId: '343243780822',
    projectId: 'dharbi-3e2b0',
    storageBucket: 'dharbi-3e2b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjN27hZEzXwFqMT8JXAsO8rx3_wL7fbOo',
    appId: '1:343243780822:ios:75e7cd9f27ad0dcbe50f77',
    messagingSenderId: '343243780822',
    projectId: 'dharbi-3e2b0',
    storageBucket: 'dharbi-3e2b0.firebasestorage.app',
    iosBundleId: 'com.example.orapayProkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjN27hZEzXwFqMT8JXAsO8rx3_wL7fbOo',
    appId: '1:343243780822:ios:75e7cd9f27ad0dcbe50f77',
    messagingSenderId: '343243780822',
    projectId: 'dharbi-3e2b0',
    storageBucket: 'dharbi-3e2b0.firebasestorage.app',
    iosBundleId: 'com.example.orapayProkit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbqIDFryQ3HRqQPp37t8DQf7MZehc9H-A',
    appId: '1:343243780822:web:44c1fb11ab05496ce50f77',
    messagingSenderId: '343243780822',
    projectId: 'dharbi-3e2b0',
    authDomain: 'dharbi-3e2b0.firebaseapp.com',
    storageBucket: 'dharbi-3e2b0.firebasestorage.app',
    measurementId: 'G-N6G5GNDDSB',
  );
}
